DROP DATABASE IF EXISTS recipe_db;
CREATE DATABASE recipe_db;
USE recipe_db;

CREATE TABLE `user` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `username` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
);

CREATE TABLE `recipe` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned DEFAULT NULL,
  `name` varchar(255) NOT NULL,
  `description` text,
  `num_of_servings` int unsigned DEFAULT NULL,
  `cook_time` int unsigned DEFAULT NULL,
  `directions` text,
  `is_publish` tinyint(1) DEFAULT '0',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `f_recipe_user_id_idx` (`user_id`),
  CONSTRAINT `f_recipe_user_id` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`)
);

-- 특정 db전용 계정 생성
-- DROP USER 'food'@'%';
-- CREATE USER 'food'@'%' IDENTIFIED BY '2052';
-- GRANT ALL PRIVILEGES ON recipe_db.* TO 'food'@'%';

insert into user (id, username, email, password, is_active, created_at, updated_at) values (1, 'ovitler0', 'tfawks0@sun.com', 'zK0>">=4\h`w', true, '2013-06-16 23:31:11', '2017-10-31 13:35:24');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (2, 'kbridgen1', 'tdemange1@loc.gov', 'tG1=+Qj(', true, '2009-09-19 21:07:09', '2001-06-03 14:07:21');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (3, 'gfarrier2', 'ohauxley2@aboutads.info', 'oZ8%bZ8w', true, '2016-02-26 08:24:58', '2017-05-01 06:25:46');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (4, 'ncripps3', 'rglenton3@friendfeed.com', 'iL3~g(u}j+e$es', false, '2012-08-29 21:30:15', '2001-03-15 20:17:21');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (5, 'cronchetti4', 'awindram4@google.nl', 'mI2&3c3qzT', true, '2016-04-08 02:09:18', '2012-10-05 05:07:14');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (6, 'kmiquelet5', 'rbeeck5@prweb.com', 'nZ7\{KelPrH(', true, '2003-04-10 13:28:32', '2021-12-16 16:51:18');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (7, 'swooding6', 'deasey6@ovh.net', 'zF3!aoL6>ja2$q+', true, '2016-04-14 22:43:36', '2004-05-11 00:40:36');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (8, 'rdyer7', 'rdone7@usgs.gov', 'wH4\061e', false, '2006-05-29 07:05:50', '2011-04-21 15:22:17');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (9, 'mingarfill8', 'kspadazzi8@infoseek.co.jp', 'yM6~3eRWaEl)W', false, '2003-01-06 08:06:54', '2016-01-17 16:20:05');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (10, 'vsouthan9', 'larchbold9@stanford.edu', 'dU0{=ql}qr3&Bu', false, '2020-04-29 05:17:03', '2009-11-12 09:33:36');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (11, 'btophama', 'fdepinnaa@ameblo.jp', 'vV1''gA@bD#_', false, '2021-06-27 23:14:53', '2009-07-17 09:55:31');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (12, 'callbrookb', 'mancliffb@people.com.cn', 'oN9|`1d|m', true, '2013-10-07 07:29:37', '2007-05-13 07:42:55');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (13, 'mlowethc', 'aminchintonc@photobucket.com', 'cF0{Rs+nI8.6/l', true, '2013-05-02 06:50:54', '2009-09-16 17:54:01');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (14, 'kellicombed', 'atomblettd@businesswire.com', 'hS9#9?kY8+c*', true, '2000-10-31 19:28:40', '2013-04-11 15:55:54');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (15, 'jbemrosee', 'vparvine@hexun.com', 'qT2~j3nq=Q<_o', false, '2002-11-21 22:58:01', '2002-01-12 23:22:19');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (16, 'kriteleyf', 'kbalcersf@jalbum.net', 'lE6\nA/ph2+>sE$z', false, '2015-02-15 19:47:24', '2017-05-19 09:13:31');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (17, 'ktumbridgeg', 'tmcdellg@indiatimes.com', 'gA9/L`>R5tSm.', false, '2006-11-03 23:32:58', '2006-08-28 04:09:14');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (18, 'tautenh', 'dgainsfordh@cdc.gov', 'pP0,QWj%CC.$#73P', false, '2020-05-05 12:16:01', '2022-02-23 14:51:26');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (19, 'lfolliti', 'asiegharti@thetimes.co.uk', 'xJ5}pp(~8zHCt', true, '2008-07-21 09:46:33', '2006-07-29 20:02:33');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (20, 'wwhetnallj', 'kdalemanj@sun.com', 'hR3/Q$pO', true, '2013-05-31 06:45:07', '2008-04-18 02:09:28');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (21, 'pjerzycowskik', 'yserotskyk@ucoz.com', 'zR9?,1fpMSev', false, '2015-09-20 14:12:21', '2016-08-07 16:51:02');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (22, 'ddibbsl', 'rmcknishl@huffingtonpost.com', 'pD5_ztKiEJ<l3R#m', true, '2005-03-15 06:44:33', '2015-08-18 12:07:15');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (23, 'jstetsonm', 'sgrishechkinm@pinterest.com', 'mG7=%)eu#|F83', false, '2000-11-28 06:58:39', '2016-10-24 15:47:23');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (24, 'hliffeyn', 'mloughheadn@amazon.de', 'dA6?j#>3', false, '2004-03-31 09:21:43', '2010-02-01 21:38:56');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (25, 'lcottomo', 'rlegono@surveymonkey.com', 'yU1>%\"o2b', false, '2008-07-22 22:58:13', '2006-01-07 11:34:13');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (26, 'dwishamp', 'fbunclarkp@newsvine.com', 'uF4_cnfNZ', false, '2006-07-16 13:05:53', '2005-09-05 05:40:48');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (27, 'rlucasq', 'alinneyq@storify.com', 'eL5,L%Xt#x', true, '2001-03-03 21:53:40', '2006-03-11 16:00:53');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (28, 'gakeherstr', 'tchorleyr@diigo.com', 'yB3|<f_nBoV.6>U|', true, '2016-10-28 04:09:23', '2021-09-15 16:20:42');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (29, 'mdimeloes', 'mbantings@japanpost.jp', 'iC3,o`1(', false, '2010-11-05 16:21:20', '2008-11-30 16:51:30');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (30, 'utroyest', 'hbraghinit@npr.org', 'tP0#IHZ|dUr)V', false, '2008-04-15 07:23:54', '2018-03-25 02:12:55');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (31, 'jeberleu', 'swaitingu@vinaora.com', 'fF9&C)W#', true, '2002-01-27 14:35:44', '2017-05-16 22:02:02');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (32, 'bcastagnev', 'mglasermanv@opera.com', 'bK5>"ZMj._B', false, '2004-07-28 22:38:19', '2010-11-01 03:53:56');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (33, 'krambergw', 'vpandyaw@blogtalkradio.com', 'uE1~w~/~HG', true, '2018-08-12 18:45:48', '2014-07-06 08:58:58');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (34, 'rrohlfx', 'jeilertx@nba.com', 'uC4\XUXky=`u''X', true, '2021-06-19 20:39:04', '2020-08-02 14:12:40');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (35, 'mallikery', 'dwhettony@opera.com', 'gM8#5="Q,=''V''6', true, '2016-01-22 14:11:04', '2021-02-11 23:34:36');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (36, 'rglasnerz', 'ewandtkez@ucoz.ru', 'iF6!rE.i0mDX?l', false, '2018-01-04 01:06:35', '2007-01-14 04:55:52');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (37, 'mcluelow10', 'gdansie10@theatlantic.com', 'pQ6`*u97O3>Lwtu', false, '2017-04-02 20:47:17', '2016-06-06 14:28:10');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (38, 'jlineham11', 'lwhorf11@webnode.com', 'fX2@zOUPL4Q', true, '2012-01-26 03:47:58', '2012-01-22 05:31:59');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (39, 'khaliburton12', 'chulburd12@blinklist.com', 'qF1}*V46<M9t''q,''', true, '2017-08-21 01:45:46', '2007-05-10 11:07:33');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (40, 'glong13', 'mhainey13@wikia.com', 'wB7).yQz,VCF''KeK', true, '2011-03-14 08:13:29', '2005-04-05 21:34:08');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (41, 'abenyon14', 'jguiett14@hud.gov', 'sP7*?A(_zb', true, '2020-10-14 13:08:56', '2009-04-09 05:37:52');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (42, 'cskittle15', 'amacdearmid15@ted.com', 'qY2@qm<ck$F&+jbg', false, '2014-08-29 23:58:17', '2015-10-13 09:40:12');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (43, 'ibuss16', 'chillhouse16@google.nl', 'nQ7!m3$&m|/@', true, '2002-01-20 12:19:59', '2003-06-15 00:25:44');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (44, 'tcorington17', 'sisson17@acquirethisname.com', 'uG6>G9x2A', true, '2009-03-28 16:21:14', '2020-01-21 08:01:14');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (45, 'ohutcheon18', 'spattington18@usa.gov', 'wJ3#OQY5YgSsR5{', true, '2009-10-03 06:50:36', '2015-04-09 23:16:31');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (46, 'mguess19', 'mgrund19@technorati.com', 'zB3){4wxn>', true, '2007-06-25 21:32:15', '2003-10-16 09:50:52');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (47, 'bscrimgeour1a', 'dmcelhinney1a@biglobe.ne.jp', 'yJ9\ZN~_/M0`8y2', true, '2005-07-23 21:54:45', '2021-12-28 06:14:38');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (48, 'mcleary1b', 'gwinspear1b@senate.gov', 'uV8|5WJ,06d', true, '2022-11-08 09:38:11', '2011-07-11 00:44:04');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (49, 'dalbert1c', 'jbonniface1c@naver.com', 'bH9>>w/1WO1yx', false, '2020-09-01 05:45:05', '2015-04-20 19:52:01');
insert into user (id, username, email, password, is_active, created_at, updated_at) values (50, 'hmedina1d', 'kdensham1d@sitemeter.com', 'wL9,$O\"', true, '2001-03-12 06:01:45', '2007-05-20 02:27:08');

insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (1, 38, 'Scanterbury', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 303, 287, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', true, '2022-01-13 09:57:06', '2023-03-29 08:08:45');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (2, 42, 'Trayford', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 541, 692, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', true, '2011-07-28 10:16:02', '2000-05-20 12:08:54');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (3, 19, 'Szwandt', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 404, 306, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, '2023-12-26 19:11:20', '2015-03-10 15:13:46');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (4, 31, 'Tembridge', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 808, 252, 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', false, '2013-06-09 00:11:01', '2016-01-04 01:40:36');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (5, 10, 'Willets', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 630, 481, 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', true, '2021-07-09 19:38:38', '2004-08-17 08:32:54');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (6, 21, 'Mogie', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 956, 418, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', false, '2017-08-12 21:37:20', '2011-12-19 10:59:12');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (7, 50, 'Troker', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 9, 0, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', false, '2006-05-11 15:21:49', '2021-01-15 16:35:18');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (8, 39, 'Pley', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 208, 629, 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', true, '2010-07-10 20:10:31', '2004-05-15 05:57:12');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (9, 27, 'Norcock', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 289, 238, 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', true, '2002-08-31 19:01:29', '2008-08-18 03:50:58');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (10, 32, 'Dunbar', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 827, 211, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, '2016-04-26 07:54:18', '2024-03-05 23:13:05');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (11, 22, 'Portam', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 701, 70, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, '2022-07-10 20:52:24', '2005-01-12 00:06:54');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (12, 47, 'Gatling', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 244, 398, 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', true, '2006-11-24 10:20:55', '2020-09-10 02:54:20');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (13, 4, 'Dennert', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 497, 424, 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', true, '2007-05-24 07:47:11', '2018-04-24 07:23:03');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (14, 18, 'Hepher', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 286, 342, 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', false, '2019-03-22 08:17:05', '2021-06-17 12:06:15');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (15, 26, 'Marlin', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 554, 217, 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', true, '2005-05-13 19:55:02', '2021-08-27 08:34:47');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (16, 5, 'Muccino', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 648, 226, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true, '2019-10-05 00:18:56', '2015-12-08 16:49:03');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (17, 36, 'Beedom', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 810, 430, 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', true, '2001-02-27 14:57:37', '2018-07-22 16:02:47');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (18, 47, 'Kryszkiecicz', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 654, 175, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', false, '2003-01-24 23:36:59', '2004-07-18 17:21:51');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (19, 23, 'Stacy', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 670, 622, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', true, '2015-04-14 09:31:59', '2001-02-19 21:16:19');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (20, 20, 'Emby', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 398, 213, 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', false, '2021-05-15 15:05:29', '2001-06-19 14:05:25');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (21, 38, 'Arrighi', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 770, 609, 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', false, '2017-09-14 03:08:18', '2023-05-13 22:22:10');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (22, 16, 'Prudence', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 782, 374, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', false, '2019-12-06 22:26:33', '2006-09-17 23:37:55');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (23, 11, 'Fleischmann', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 356, 348, 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', false, '2012-05-15 22:39:31', '2024-08-01 15:58:57');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (24, 1, 'Orfeur', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 257, 56, 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', false, '2014-10-23 02:38:44', '2023-06-28 21:38:44');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (25, 31, 'Dargavel', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 162, 425, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', true, '2023-09-10 07:39:14', '2003-01-03 16:13:35');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (26, 15, 'Bresson', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 360, 581, 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', false, '2017-10-10 00:40:48', '2001-07-16 01:04:18');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (27, 48, 'Iannitti', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 226, 662, 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', false, '2008-11-07 14:06:49', '2005-08-20 02:30:14');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (28, 29, 'Cuckoo', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 867, 400, 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', true, '2004-09-13 07:14:59', '2019-01-15 13:19:53');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (29, 23, 'Derham', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 344, 717, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', false, '2005-05-14 20:03:08', '2003-02-28 04:11:36');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (30, 18, 'Payle', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 848, 778, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', true, '2004-10-17 02:52:58', '2000-07-31 06:44:15');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (31, 45, 'Sprey', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 71, 213, 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', false, '2022-04-10 21:52:20', '2003-08-25 19:33:08');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (32, 17, 'Butson', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 395, 105, 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', false, '2007-07-04 12:10:46', '2016-03-25 00:37:56');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (33, 49, 'Hattiff', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 70, 882, 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', false, '2020-12-09 12:41:18', '2018-12-09 17:25:44');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (34, 38, 'Dilworth', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 679, 532, 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', false, '2023-03-13 18:26:09', '2015-08-01 15:03:23');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (35, 34, 'Whitebrook', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 65, 475, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '2012-06-26 12:39:25', '2012-05-13 01:32:25');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (36, 28, 'Hamblin', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 247, 779, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', false, '2002-11-07 20:16:38', '2005-10-22 20:59:08');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (37, 17, 'Coggan', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 86, 685, 'In congue. Etiam justo. Etiam pretium iaculis justo.', true, '2023-09-09 23:15:22', '2017-11-13 09:09:13');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (38, 3, 'MacRury', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 885, 751, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', false, '2024-04-17 01:54:45', '2005-04-19 17:54:15');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (39, 27, 'Hause', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 893, 459, 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', true, '2011-03-15 05:53:30', '2004-08-08 10:55:54');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (40, 38, 'Cork', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 174, 54, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', false, '2005-07-13 00:17:46', '2005-10-23 21:06:30');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (41, 10, 'Bruckstein', 'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 733, 175, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', true, '2017-11-06 07:22:33', '2004-03-10 21:13:47');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (42, 36, 'Walworth', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 720, 544, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', false, '2023-01-07 09:12:58', '2022-11-04 02:40:41');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (43, 46, 'Straneo', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 313, 754, 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', false, '2015-11-12 19:59:23', '2005-05-07 20:37:16');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (44, 36, 'Jinkinson', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 353, 469, 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', false, '2014-01-15 19:35:43', '2014-05-23 13:15:48');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (45, 19, 'Kesten', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 571, 677, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', false, '2021-05-11 18:13:20', '2011-01-21 20:29:40');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (46, 22, 'Pisco', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 31, 108, 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', false, '2013-04-21 12:09:40', '2021-12-23 03:53:54');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (47, 50, 'Donan', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 816, 742, 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', false, '2002-07-08 21:33:22', '2006-08-14 06:15:22');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (48, 34, 'Coltherd', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 532, 514, 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', true, '2010-04-13 08:52:08', '2014-07-11 07:06:56');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (49, 34, 'Durrad', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 749, 356, 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', true, '2023-02-15 15:49:54', '2005-03-30 07:56:18');
insert into recipe (id, user_id, name, description, num_of_servings, cook_time, directions, is_publish, created_at, updated_at) values (50, 32, 'Cherrison', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 635, 418, 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', true, '2007-10-06 18:00:24', '2014-10-23 21:00:08');

-- 타임존 설정 | 타임스탬프의 시간이 이상하게 찍힐 경우
-- SET time_zone = 'Asia/Seoul';

-- 테이블 조회
SELECT * FROM user;
SELECT * FROM recipe;

-- 실험용 쿼리
INSERT INTO recipe (name, description, num_of_servings, cook_time, directions)
VALUES ('Recipe Name', 'Recipe Description', 4, 45, 'Recipe Directions');

SELECT * FROM recipe LIMIT 0, 25;

UPDATE recipe
SET is_publish = NOT is_publish
WHERE id = 101;

DELETE FROM user WHERE username = 'Gill-dong Hong';

SELECT * FROM user WHERE email = 'joseon@korea.kr';

SELECT user_id FROM recipe WHERE id = 57;